[workspace]
resolver = "3"
members = ["lunova_client", "lunova_server"]

# [package]
# name = "lunova"
# version = "0.0.0-alpha"

[workspace.dependencies]
tokio = { version = "1.49.0", features = ["full"] }
