[package]
name = "lunova_client"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
mirl = { workspace = true }
lunova_lib = { path = "../lunova_lib" }

[lints]
workspace = true
