[package]
name = "lunova_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
mirl = { workspace = true }
indexmap = { workspace = true }
bitcode = { version = "0.6.9" }
postcard = { version = "1.1.3" }
wincode = { version = "0.4.4" }

[lints]
workspace = true
